### ISSUE TITLE
UI Changes

### ISSUE THREAD

**Issue by harrycode007** [harrycode007/BBCNewsApp#4]

**Comment by Sweta271097** [comment]
Hello, 

Can you please give an idea about the kind of UI changes you require?

**Comment by harrycode007** [comment]
Hello,

Some of the UI changes that you could make.

1) Change the color of the text in      the headlines.
2) Color of the web loader.
3) You can also try changing the listview to cardview.
4) You can make these changes in the XML files.

Further, if you have any ideas, you can go ahead and improve the UI. But
just make sure you inform me.

Regarding the technical issues, I will list them by tomorrow.

Regards,
Hariharan K.

>

**Comment by harrycode007** [comment]
Hello,

I have updated my GitHub with the issues you can work on.
If you have any questions please let me know via email or gitter.

Thank you.

Regards,
Hariharan K,
Btech , 2nd Year CSE,
GitHub <https://github.com/harrycode007> | Blog
<https://harry007854440969.wordpress.com/> | FOSS@Amrita
<https://amfoss.in/accounts/181/>
