### ISSUE TITLE
Create Cardview instead of Listview

### ISSUE THREAD

**Issue by harrycode007** [harrycode007/BBCNewsApp#5]
The news headlines have been listed in a listview. Use cardview instead of listview. For this you will have to make changes in the xml files.

**Comment by thedevelopersanjeev** [comment]
I want to work on this issue...

**Comment by harrycode007** [comment]
Hello,

Great to hear that. You can go ahead and work on it. If you have any
doubts, do let me know.

Regards
Hariharan K.
